#!/bin/bash

percentage=$(acpi | grep -Po "[0-9].\%")
percentage=${percentage::-1}

remaining_time=$(acpi | grep -Po "[0-9].\:[0-9].\:")

color="#$(printf "%02x%02x" $(echo "(100-$percentage)*240/100" | bc) $(echo "$percentage*255/100" | bc))00"

[[ $(acpi) == *"Discharging"* && 7 -gt $percentage ]] && i3-nagbar -m "Battery critical!" &
[[ $(acpi) == *"Charging"* ]] && text="CHARGING" || text="$percentage%  ${remaining_time::-1}"

printf "<tt>%s%s</tt>\n" "$(/home/$USER/.config/i3/pango_bar $percentage 0 100 18 "${text}" $color "#333")"
