#!/bin/bash

[[ -n $1 ]] && dunstctl set-paused toggle

text='<span fgcolor="#68bc1e"><tt> <span size="small">dunst</span> </tt></span>'
[[ $(dunstctl is-paused) == *"true"* ]] && text='<span fgcolor="#e28888" strikethrough="true"><tt> <span size="small">dunst</span> </tt></span>' #⏻ 

echo '<span bgcolor="#223" size="large">'${text}'</span>'
