#!/bin/bash

fgcolor="#888"
bgcolor="#222"
width=60

if [ -n $1 ]; then
    if [[ $1 == "3" ]]; then 
        ~/.config/i3/mediakey.sh &
    elif [[ $1 == "1" ]]; then
        ~/.config/i3/mediakey.sh play-pause
    fi
fi

if [ $(~/.config/i3/mediakey.sh status) == "Playing" ]; then
    fgcolor="#1db954"
fi

status="$(~/.config/i3/mediakey.sh metadata --format "{{ title }} ‒ {{ artist }}")"

# Apparently, i3blocks or pango do not play nicely with &
status=${status/&/&amp;}

if [ ${#status} -gt $width ]; then
    ms=$(echo "(4*$(date +%s)) % (${#status}-$width+7)-4" | bc)
    [[ $ms -lt 0 ]] && ms=0 
    [[ ${#status}-$ms -lt $width ]] && ms=${#status}-$width
    status="${status:ms:width}"
fi

printf '<span fgcolor="%s">%s</span> <span weight="600" font_family="Mono" bgcolor="%s" fgcolor="%s">▏%s▕</span>\n' $fgcolor "($(playerctl -ls | wc -l))" "$bgcolor" "$fgcolor"  "${status:=No Playback}" 

