#!/bin/bash

storage=$(df -h /home/ --output=pcent,avail | tail -1)
storage_used=$(echo $storage | cut -d ' ' -f1)
storage_avail=$(echo $storage | cut -d ' ' -f2)


color="#$(printf "%02x%02x00" $(echo "${storage_used::-1}*255/100" | bc) $(echo "(100-${storage_used::-1})*255/100" | bc))"

bgcolor="#364D38"
color="#48AA54"
if [[ $percentage -gt 40 ]]; then color="#3A7F85"; bgcolor="#243233"; fi
if [[ $percentage -gt 70 ]]; then color="#DB995D"; bgcolor="#332B24"; fi
if [[ $percentage -gt 90 ]]; then color="#BB3D37"; bgcolor="#332424"; fi

printf "<span size='medium' bgcolor='$bgcolor' fgcolor='#ccc'>  DISK <tt>%s</tt></span>\n" "$(/home/$USER/.config/i3/pango_bar ${storage_used::-1} 0 100 9 $storage_avail $color $bgcolor)"
