#!/bin/bash

# Width of the bar in characters
width=35
bar="█░"

if [[ -z $1 || -z $2 || -z $3 ]]; then
    echo "Usage: bar <state> <min> <max> [chars] [transparent?]"
    exit
fi

# Optional parameter bar width
[[ -z $4 ]] || width=$4

# Two "reduced" styles of bar 
[[ "$5" == "less" ]] && bar="▒░"
[[ "$5" == "barely" ]] && bar="░ "

# Compute number of characters to actually fill
filled_flt=$(printf "%.2f" $(echo "scale = 2; ($1-$2)/($3-$2)*$width" | bc))
filled=$(echo $filled_flt | grep -Po "([0-9]+)" | head -n 1)

[[ $(($1-$2)) -gt 0 ]]        && printf "%0.s${bar:0:1}" $(seq 1 $filled)
[[ $((width-filled)) -gt 0 ]] && printf "%0.s${bar:1:1}" $(seq $((filled+1)) $((width)))
printf "▏"
